spring:
  application:
    name: zuul
  rabbitmq:
    host: 10.21.30.23
    port: 5672
    username: guest
    password: guest
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
        
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
